# This rule is not used by the project bb-dist-noti-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the node-role.bb-noti.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bb-dist-noti-operator
    app.kubernetes.io/managed-by: kustomize
  name: leaderstatuschecker-editor-role
rules:
- apiGroups:
  - node-role.bb-noti.io
  resources:
  - leaderstatuscheckers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node-role.bb-noti.io
  resources:
  - leaderstatuscheckers/status
  verbs:
  - get
