# This rule is not used by the project bb-dist-noti-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over node-role.bb-noti.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bb-dist-noti-operator
    app.kubernetes.io/managed-by: kustomize
  name: leaderstatuschecker-admin-role
rules:
- apiGroups:
  - node-role.bb-noti.io
  resources:
  - leaderstatuscheckers
  verbs:
  - '*'
- apiGroups:
  - node-role.bb-noti.io
  resources:
  - leaderstatuscheckers/status
  verbs:
  - get
