---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - node-role.bb-noti.io
  resources:
  - leaderstatuscheckers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node-role.bb-noti.io
  resources:
  - leaderstatuscheckers/finalizers
  verbs:
  - update
- apiGroups:
  - node-role.bb-noti.io
  resources:
  - leaderstatuscheckers/status
  verbs:
  - get
  - patch
  - update
